### ISSUE TITLE
Typo on the Faucet View php file name

### ISSUE THREAD

**Issue by gcarreno** [pasichDev/noso-faucet#14]
Hey Andrii (@pasichDev),

The file is named `faucetVIew.php` but should be named `faucetView.php`.

Remember that filenames in *nix environments are case sensitive. It may work in a Windows environment, but it's going boom on my Linux :smiley: 

Cheers,
Gus

**Comment by pasichDev** [comment]
Hello @gcarreno , fixed!

**Comment by gcarreno** [comment]
Cool, closing!
