### ISSUE TITLE
FYI: Why I included guzzle

### ISSUE THREAD

**Issue by gcarreno** [pasichDev/noso-faucet#16]
Hey Andrii (@pasichDev),

You're probably wondering why I included guzzle on the requirements for this project.

I did it because you were getting info about accounts via the Explorer API. I then had a look for the most used HTTP client in the PHP world and it's the guzzle one.

That's the reason behind including the guzzle HTTP Client.
Doesn't mean it needs to be there.
If you find that guzzle is not for you or it's too heavy for such a small project, please feel free to use another.

Cheers,
Gus

**Comment by pasichDev** [comment]
Okay, I will consider this point in more detail and then I will give an answer!
@gcarreno

**Comment by pasichDev** [comment]
Hi @gcarreno , it was not a problem for me to switch to guzzle. Your suggestion was a good idea as we need to take care of the future of our project!

**Comment by gcarreno** [comment]
Hey Andrii (@pasichDev),

I'm glad you were able to get familiarized with guzzle.

Personally, I don't remember ever using it, since `CakePHP` comes with it's own HTTP Client.
But this was the top one on `packagist.org`, so I added it as a suggestion on my template.

This matter seams to be resolved, so I'll close this issue.

Cheers,
Gus
