### ISSUE TITLE
Have a clean webroot folder with no code

### ISSUE THREAD

**Issue by gcarreno** [pasichDev/noso-faucet#2]
Hey @pasichDev,

Would it be OK if you modified your folder structure to the following?
- config/
    - .env <-- Use the ENV functionalities to store the local private data, like DB passwords and API keys
    Have a look at: https://packagist.org/packages/vlucas/phpdotenv
- src/
    - (All the code)
- webroot/
    - index.php <-- this has little to no code and just gets all the functionality from the src folder above
    - .htaccess
    - img/
        - (all the images)
    - js/
        - (all the Javascript)
    - css/
        - (all the Cascading Style Sheets)
- README.md
- LICENSE
- .gitignore
- .gitattributes

This way when we create the virtual host on apache2, we point it at the folder `webroot`.
This leaves all the code OUTSIDE the `webroot` folder and apache cannot serve it, so no need for the `defined(pasich) or die()`.

This will also begin to prepare you folder structure to use `composer`.
We need to have a talk about Name Spaces on your classes and probably use a better HTTP Client to access the explorer API.

But the `composer` stuff can wait, first the folder structure, please :smiley: 

Many, many thanks!!

Cheers,
Gus

**Comment by pasichDev** [comment]
Hey @gcarreno I have noticed your question. I'm already halfway to a solution.
