### ISSUE TITLE
Is it somehow more logical to determine whether the user is authorized or not?

### ISSUE THREAD

**Issue by pasichDev** [pasichDev/noso-faucet#20]
This applies to authorization and ref links, it's best to create a separate class for checking

**Comment by gcarreno** [comment]
Hey Andrii (@pasichDev),

There are two aspects when we generalize with the word Auth:
1. Authentication
2. Authorization

With :one: a simple login procedure is needed as long as we don't have separate levels for each user.
When we do have separate levels for users, we have to add :two: as well.

The login identifies the user(:one:), but then the user has to be restricted to some areas/information(:two:)

This project requires :one: and :two:.

Cheers,
Gus
<hr>
P.S.: This is more suited to be a discussion and not an issue.

**Comment by pasichDev** [comment]
Hi @gcarreno ,I used this as a mini note, I know what the thing is about, I just wanted to remember

**Comment by gcarreno** [comment]
Hey Andrii (@pasichDev),

That's kewl, I'll get out of your way and let you manage it, then, as you see fit :smiley: 

Cheers,
Gus
<hr>
P.S.:I spell cool in an alternative phonetic way: kewl
It's not a mystery word, it's just me playing around with spellings that sound the same, but makes them unique to me :smiley:

**Comment by pasichDev** [comment]
done
