### ISSUE TITLE
Problems IMPORTANT

### ISSUE THREAD

**Issue by pasichDev** [pasichDev/noso-faucet#22]
**1. Clearing cookies after ref authorization, namely deleting ref cookies!**

**Comment by pasichDev** [comment]
- [+ ] N44pzj8pJ6M63fmJT22QuXbqN3vSiDG

**Comment by gcarreno** [comment]
Hey Andrii (@pasichDev),

Is this just for your memory aid or are you asking for help on this subject?

Cheers,
Gus

**Comment by pasichDev** [comment]
hi @gcarreno , just for memory)

**Comment by gcarreno** [comment]
Hey Andrii (@pasichDev),

Awesome sauce then. I'll leave you to it. :smiley: 

Cheers,
Gus

**Comment by pasichDev** [comment]
DONE
