### ISSUE TITLE
Dangerously close to reinventing the wheel

### ISSUE THREAD

**Issue by gcarreno** [pasichDev/noso-faucet#24]
Hey Andrii (@pasichDev),

Might as well say this now, in these early stages, than say it later when you've invested too much time in this architecture.

With a router(/dispatcher), a semblance of controllers and a very rudimentary layout/templating system, we are now in the middle of `SlimPHP`'s territory.

So my arguments are these:
- Granted, you don't need a framework for this, but by using one you don't have to create and test the boilerplate code for the basics.
- At the moment, your code is functional but lacks any ways of testing it via automation, the Continuous Integration of the CI/CD pair.

Yes, you can curse me and throw a fit of rage, cuz in essence this would be another re-write :frowning_face:
Hence me creating this issue now, so we can discuss this possible change of path.
**Hint**: This should be a discussion and I think you should open that area on the Project settings :smiley: 

Have you ever done any work using the `SlimPHP` framework?
At the moment, `SlimPHP` is the most light weight of all the PHP frameworks, usually used for very simple projects or for rapid prototyping of a possible more complex one.

What are your thoughts on this subject?

Cheers,
Gus
<hr>

1. https://www.slimframework.com/
2. https://github.com/slimphp

**Comment by pasichDev** [comment]
hi @gcarreno , I opened the discussion
[https://github.com/pasichDev/noso-faucet/discussions/25](url)
