### ISSUE TITLE
How to use cookies?

### ISSUE THREAD

**Issue by pasichDev** [pasichDev/noso-faucet#27]
Hello @gcarreno , I didn't understand how to use cookies in Slim PHP

**Comment by gcarreno** [comment]
Hey Andrii (@pasichDev),

According to [this migration guide](https://www.slimframework.com/docs/v3/start/upgrade.html#cookies) from 3.0 and upwards the cookies code is no longer part of the core and they suggest using [FIG Cookies](https://github.com/dflydev/dflydev-fig-cookies) as the package that deals with cookies.

This is just from a quick search. It needs a bit more info, I know, and I'm sorry I couldn't provide it.

Cheers,
Gus

**Comment by pasichDev** [comment]
Hey @gcarreno , I've looked at a lot of options. Stopped at this implementation. Can we use it?

[https://stackoverflow.com/a/64368648](url)

**Comment by pasichDev** [comment]
hi @gcarreno , solved
