### ISSUE TITLE
Needs a DB Schema to create the tables.

### ISSUE THREAD

**Issue by gcarreno** [pasichDev/noso-faucet#3]
Hey @pasichDev,

Could you please include a SQL file that has the `CREATE DATABASE` and the `CREATE TABLE` entries?

Need that in advance since you're also not implementing migrations.

Cheers,
Gus

**Comment by pasichDev** [comment]
ok, I'll include the database file in a few hours.

**Comment by gcarreno** [comment]
> ok, I'll include the database file in a few hours.

AWESOME!!

Thanks :smiley: 

Cheers,
Gus

**Comment by gcarreno** [comment]
This is done, closing :+1:
