### ISSUE TITLE
What is the purpose of locking as resolved?

### ISSUE THREAD

**Issue by gcarreno** [pasichDev/noso-faucet#6]
Hey @pasichDev,

You're locking the issues that you already solved as `locked as resolved`. I wasn't aware of this possibility but it makes no sense for closed issues, at least in my point of view.

Since you locked comments to only collaborators, and I'm not one, I can't comment on any issue after you locked it, either open or closed.

If this is a common practice, I haven't seen it yet and you can probably explain it to me :)

Many thanks in advance.

Cheers,
Gus

**Comment by pasichDev** [comment]
Hello @gcarreno , I invited you to be a co-author. And about the removal of the question, was not attentive, sorry!

**Comment by gcarreno** [comment]
Hey @pasichDev,

Okies, I've accepted your invite. Many thanks!!

Sorry, but I did not understood what you mean by:
> And about the removal of the question, was not attentive, sorry!

Cheers,
Gus

**Comment by pasichDev** [comment]
Hi @gcarreno ,
I meant that I was inattentive when closing questions.

**Comment by pasichDev** [comment]
I think the question is exhausted
