### ISSUE TITLE
These are suggestion due to my obessive compulsion to have things readable...

### ISSUE THREAD

**Issue by gcarreno** [pasichDev/noso-faucet#7]
Hey @pasichDev,

I've just had a quick look at your changes and I think you did great, with even picking up a bit of the MVC with controllers :smiley: 

I would wish that you would use `CamelCase` in your code's name spaces and/or classes, but again, not necessary for the code to work.

I have this compulsion to make my code as readable as possible, so I tend to adhere to a lot of the PHP conventions(not rules, I know) that I've picked up with 15+ years on PHP, but this does not mean that everybody should be as "_anal_" as I am :smiley: 

I have this thing about an unspoken rule that involves lead programmers being killed by buses. If they are killed, and the code they leave behind is only readable/understandable to that dev, then the poor dev that comes to continue that code will have a very bad time. And I'm a firm believer of : Do unto others, like you would want others do unto you.

All in all, I love that you were able to understand my template and you even did a mini router and controller!! This means you really have a good understanding of how it should be :smiley: 

Congrats!!

Cheers,
Gus

**Comment by pasichDev** [comment]
Hi @gcarreno , i understand you, everything is fine! I think we can close the question!
